* if we have more number of categorical data in the data set for ordinal dtype, it tough to do the one hot encoding, so we use the ordinal encoding or label encoding here
* we can use for fixed number of categories, so its too easier.

In [3]:
import pandas as pd
import numpy as np
import datetime

In [5]:
base = datetime.datetime.today()
base_list = [ base - datetime.timedelta(days = x) for x in range(0,20)]
df = pd.DataFrame(base_list)
df.columns = ['day']

In [6]:
df

                          day
0  2021-08-30 13:40:10.249448
1  2021-08-29 13:40:10.249448
2  2021-08-28 13:40:10.249448
3  2021-08-27 13:40:10.249448
4  2021-08-26 13:40:10.249448
5  2021-08-25 13:40:10.249448
6  2021-08-24 13:40:10.249448
7  2021-08-23 13:40:10.249448
8  2021-08-22 13:40:10.249448
9  2021-08-21 13:40:10.249448
10 2021-08-20 13:40:10.249448
11 2021-08-19 13:40:10.249448
12 2021-08-18 13:40:10.249448
13 2021-08-17 13:40:10.249448
14 2021-08-16 13:40:10.249448
15 2021-08-15 13:40:10.249448
16 2021-08-14 13:40:10.249448
17 2021-08-13 13:40:10.249448
18 2021-08-12 13:40:10.249448
19 2021-08-11 13:40:10.249448

In [46]:
li = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'
     'monday','tuesday','wednesday','thursday','friday','saturday','sunday',
     'monday','tuesday','wednesday','thursday','friday','saturday','sunday']

In [47]:
df['dat_of_week'] = li

In [48]:
df

                          day   dat_of_week
0  2021-08-30 13:40:10.249448        monday
1  2021-08-29 13:40:10.249448       tuesday
2  2021-08-28 13:40:10.249448     wednesday
3  2021-08-27 13:40:10.249448      thursday
4  2021-08-26 13:40:10.249448        friday
5  2021-08-25 13:40:10.249448      saturday
6  2021-08-24 13:40:10.249448  sundaymonday
7  2021-08-23 13:40:10.249448       tuesday
8  2021-08-22 13:40:10.249448     wednesday
9  2021-08-21 13:40:10.249448      thursday
10 2021-08-20 13:40:10.249448        friday
11 2021-08-19 13:40:10.249448      saturday
12 2021-08-18 13:40:10.249448        sunday
13 2021-08-17 13:40:10.249448        monday
14 2021-08-16 13:40:10.249448       tuesday
15 2021-08-15 13:40:10.249448     wednesday
16 2021-08-14 13:40:10.249448      thursday
17 2021-08-13 13:40:10.249448        friday
18 2021-08-12 13:40:10.249448      saturday
19 2021-08-11 13:40:10.249448        sunday

In [30]:
print(li)

None

In [49]:
dic = {'monday':1,'tuesday':2,'wednesday':3,'thursday':4,'friday':5,'saturday':6,'sunday':7}

In [50]:
df['dat_of_week'] = df['dat_of_week'].map(dic)

In [56]:
df['dat_of_week'] = df['dat_of_week'].values.astype(int)

In [57]:
df.head()

                         day  dat_of_week
0 2021-08-30 13:40:10.249448            1
1 2021-08-29 13:40:10.249448            2
2 2021-08-28 13:40:10.249448            3
3 2021-08-27 13:40:10.249448            4
4 2021-08-26 13:40:10.249448            5