In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv('train_titanic.csv', usecols = ['Cabin','Survived'])

In [3]:
data.head()

   Survived Cabin
0         0   NaN
1         1   C85
2         1   NaN
3         1  C123
4         0   NaN

In [4]:
data['Cabin'].fillna('Missing', inplace = True)

In [9]:
data['Cabin'].unique()

array(['M', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [7]:
data['Cabin'] = data['Cabin'].astype(str).str[0]

In [8]:
data['Cabin'].unique()

array(['M', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [12]:
prob = data.groupby(['Cabin'])['Survived'].mean() # finding the percentage.

In [14]:
prob = pd.DataFrame(prob)

In [15]:
prob.head()

       Survived
Cabin
A      0.466667
B      0.744681
C      0.593220
D      0.757576
E      0.750000

In [18]:
prob['died'] = 1-prob['Survived']

In [19]:
prob.head()

       Survived      died
Cabin
A      0.466667  0.533333
B      0.744681  0.255319
C      0.593220  0.406780
D      0.757576  0.242424
E      0.750000  0.250000

In [20]:
prob['ratio'] = prob['Survived']/prob['died']

In [21]:
prob

       Survived      died     ratio
Cabin
A      0.466667  0.533333  0.875000
B      0.744681  0.255319  2.916667
C      0.593220  0.406780  1.458333
D      0.757576  0.242424  3.125000
E      0.750000  0.250000  3.000000
F      0.615385  0.384615  1.600000
G      0.500000  0.500000  1.000000
M      0.299854  0.700146  0.428274
T      0.000000  1.000000  0.000000

In [23]:
a = prob['ratio'].to_dict()

In [25]:
data['Cabin'] = data['Cabin'].map(a)

In [26]:
data.head()

   Survived     Cabin  died
0         0  0.428274     1
1         1  1.458333     0
2         1  0.428274     0
3         1  1.458333     0
4         0  0.428274     1

In [27]:
data.drop('died',axis =1, inplace = True)

In [28]:
data.head()

   Survived     Cabin
0         0  0.428274
1         1  1.458333
2         1  0.428274
3         1  1.458333
4         0  0.428274